### ISSUE TITLE
fails to build with new asio 1.34.2

### ISSUE THREAD

**Issue by david-geiger** [codership/galera#679]
Hi,

On Mageia Cauldron galera fails to build with new asio 1.34.2 due to:

> In file included from /home/iurt/rpmbuild/BUILD/galera-26.4.22-build/galera-26.4.22/galerautils/src/gu_asio.cpp:26:
/home/iurt/rpmbuild/BUILD/galera-26.4.22-build/galera-26.4.22/galerautils/src/gu_asio_io_service_impl.hpp:19:10: fatal error: asio/io_service.hpp: No such file or directory
   19 | #include "asio/io_service.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Attached full build log:

[build.x86_64.0.20250618041606.log](https://github.com/user-attachments/files/20789064/build.x86_64.0.20250618041606.log)

**Comment by janlindstrom** [comment]
https://jira.mariadb.org/browse/MDEV-36926

**Comment by ottok** [comment]
Where is the exact source of Mageia Cauldron spec file? Did it build on any previous version of ASIO or is this the first time you are building with system ASIO?

Related: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1115369

**Comment by david-geiger** [comment]
The exact source of Mageia Cauldron spec file is here:
https://svnweb.mageia.org/packages/cauldron/galera/current/SPECS/

Yes before asio 1.34.x it built well with system asio.

**Comment by ottok** [comment]
> The exact source of Mageia Cauldron spec file is here: https://svnweb.mageia.org/packages/cauldron/galera/current/SPECS/
> 
> Yes before asio 1.34.x it built well with system asio.

Are you sure your builds were using the system ASIO library and not the embedded copy of ASIO in Galera sources? Do you have a build log that proves that Galera ever built with ASIO 1.3x?

I don't see any changes in https://svnweb.mageia.org/packages/cauldron/galera/releases/26.4.21/1.mga10/SPECS/galera.spec?revision=2149349&view=markup or e.g. https://svnweb.mageia.org/packages/cauldron/galera/releases/26.4.21/1.mga10/SOURCES/cmake_paths.patch?revision=2149349&view=markup that would modify how you build Galera so that it would use system ASIO instead of the embedded ASIO. The build log you attached seems to have `-DHAVE_ASIO_HPP` passed to the compiler but no confirmation of what ASIO library or version it tried to use (although the build is failing to find ASIO, so actually we should see an old log to confirm if it ever used anything else than the embedded ASIO copy).

**Comment by ottok** [comment]
Potential fix filed as #691.
