### PR TITLE
Port ASIO usage to ASIO 1.33+ API

### LINKED ISSUE #679: fails to build with new asio 1.34.2
Hi,

On Mageia Cauldron galera fails to build with new asio 1.34.2 due to:

> In file included from /home/iurt/rpmbuild/BUILD/galera-26.4.22-build/galera-26.4.22/galerautils/src/gu_asio.cpp:26:
/home/iurt/rpmbuild/BUILD/galera-26.4.22-build/galera-26.4.22/galerautils/src/gu_asio_io_service_impl.hpp:19:10: fatal error: asio/io_service.hpp: No such file or directory
   19 | #include "asio/io_service.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Attached full build log:

[build.x86_64.0.20250618041606.log](https://github.com/user-attachments/files/20789064/build.x86_64.0.20250618041606.log)

### PR DESCRIPTION
**Pull request by ottok**
ASIO 1.33+ removed several legacy APIs and builds started failing on:

    gu_asio_io_service_impl.hpp:19:10: fatal error: asio/io_service.hpp: No such file or directory

Change the resolver helpers to return a plain endpoint instead of an iterator or results_type. This avoids depending on the return type of resolve(), which changed between versions.

Gate the remaining API differences with #if ASIO_VERSION >= 101200 so the code uses the modern names (make_address, asio::post, restart, expires_after) when available and falls back to the legacy names otherwise.

Closes: #679

Related: https://jira.mariadb.org/browse/MDEV-36926

### CODE REVIEW

**Comment by ottok** [comment]
This is in use now in my Debian packaging and seems to work, but feedback/review would be appreciated.

**Comment by grooverdan** [comment]
Great work. Good to see!

Few packaging issues - https://buildbot.mariadb.org/#/grid?branch=refs%2Fpull%2F57%2Fhead - fix there, feel free to cherry-pick/reword.

There we some other compile errors worth correcting too in the CI results, use after free and potentially other important ones.

**Comment by ottok** [comment]
Thanks for initial review! This is not really my strong area but the feedback indicates that the general approach I took is correct so I will continue to polish this.

**Comment by janlindstrom** [comment]
@ottok Repository should be git@github.com:mariadb-corporation/codership-galera.git  and branch mariadb-4.x

**Comment by mariadb-TeemuOllakka** [comment]
Hi @ottok!

The patch looks good for a temporary solution to get Debian build to pass.

However, 
* It does not fix all the issues I mentioned in https://jira.mariadb.org/browse/MDEV-36926?focusedCommentId=307360&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-307360
* This patch removes the whole bundled ASIO which may still needed for some legacy platforms we build for. There may also be some builders which don't have ASIO development header installed and still needed the bundled library.

@grooverdan please don't merge this in yet to avoid surprises in downstream merges.

I have a fix ready which passes with wide range of ASIO versions, but I need to run it through all builders to ensure that there are no regressions. This will probably take a day or two.

**Comment by grooverdan** [comment]
> @ottok Repository should be [git@github.com](mailto:git@github.com):mariadb-corporation/codership-galera.git and branch mariadb-4.x

It was good to see this PR public, even if only briefly :disappointed: .

Looking forward to seeing this merged to https://github.com/MariaDB/galera mariadb-4.x upon completion so it can build and run the CI against the server.

> Hi @ottok!
> 
> The patch looks good for a temporary solution to get Debian build to pass.
> 
> However,
> 
>     * It does not fix all the issues I mentioned in https://jira.mariadb.org/browse/MDEV-36926?focusedCommentId=307360&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-307360
> 
>     * This patch removes the whole bundled ASIO which may still needed for some legacy platforms we build for. There may also be some builders which don't have ASIO development header installed and still needed the bundled library.

* RHEL 7 is 1.10.8
* RHEL 8 is 1.12.0, however its include headers are under boost /usr/include/boost/asio/version.hpp
* SLES/OpenSUSE also have Asio bundled under boost
 
> @grooverdan please don't merge this in yet to avoid surprises in downstream merges.

I had no intention to do so.

> I have a fix ready which passes with wide range of ASIO versions, but I need to run it through all builders to ensure that there are no regressions. This will probably take a day or two.

great.

**Comment by janlindstrom** [comment]
There is already https://github.com/mariadb-corporation/codership-galera/pull/1123 related to MDEV-36926 Support building against Asio 1.14.1 through 1.38.0

**Comment by ottok** [comment]
> There is already https://github.com/mariadb-corporation/codership-galera/pull/1123 related to MDEV-36926 Support building against Asio 1.14.1 through 1.38.0

The page yields "error 404" to me, and also the Jira MDEV-36926 didn't mention anyone working on this or that there is an existing PR.

Now with multiple people jumping on this in recent days seems there is a fix coming from upstream any any additional iterations from me on this PR would be wasted effort, so I will close this now to avoid duplicate work.
