### ISSUE TITLE
Galera does not compile with GCC 4.9.1

### ISSUE THREAD

**Issue by philip-galera** [codership/galera#162]
```
gcc -o galerautils/src/gu_fifo.os -c -std=c99 -fno-strict-aliasing -pipe -g -O3 -DNDEBUG -m64 -Wall -Wextra -Wno-unused-parameter -pedantic -fPIC -pthread -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H -DGALERA_USE_GU_NETWORK -DHAVE_BYTESWAP_H -DHAVE_ENDIAN_H -DHAVE_BOOST_SHARED_PTR_HPP -DHAVE_TR1_UNORDERED_MAP -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG=1 -DHAVE_ASIO_HPP -DHAVE_ASIO_SSL_HPP -Werror -I. -Iasio -Icommon -Igalerautils/src -Igcomm/src -Igcomm/src/gcomm -Igcache/src -Igcs/src -Iwsdb/src -Igalera/src galerautils/src/gu_fifo.c
In file included from /usr/include/stdio.h:27:0,
                 from galerautils/src/gu_fifo.c:18:
/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^
cc1: all warnings being treated as errors
```

Suggested fix:

```
diff --git a/galerautils/src/gu_fifo.c b/galerautils/src/gu_fifo.c
index 03c8644..1adde9a 100644
--- a/galerautils/src/gu_fifo.c
+++ b/galerautils/src/gu_fifo.c
@@ -13,7 +13,7 @@
  * minimum space when there are few items in the queue.
  */

-#define _BSD_SOURCE
+#define _DEFAULT_SOURCE

 #include <stdio.h>
 #include <string.h>
```
